# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftFirstAPP' do


  pod 'AFNetworking', '~>3.1.0'
  pod 'SDWebImage', '~> 3.7.2'
  pod 'MBProgressHUD', '~> 0.9.1'




  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftFirstAPP

  target 'SwiftFirstAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftFirstAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
